import type { NextPage } from "next";
import Head from "next/head";
import { BestSelling, Carousel, CategoryTiles, Perks } from "../components";

const Home: NextPage = () => {
  return (
    <div className="mx-5">
      <Head>
        <title>ELCTRX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel />
      <CategoryTiles />
      <Perks />
      <BestSelling />
    </div>
  );
};

export default Home;
